// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package forge_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Liphium/magic/backend/views/components"

func NewForgeStep1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col gap-4 justify-start items-start\"><p class=\"text-middle-text\">Select a repository for your Forge.</p><div hx-get=\"/a/panel/_forms/repository/installations\" hx-swap=\"outerHTML\" hx-headers=\"{&#34;M-SubmitURL&#34;: &#34;/a/panel/forge/new&#34;}\" hx-trigger=\"load\"><p>Loading repositories..</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func NewForgeSidebar() templ.Component {
	return components.Sidebar([]components.SBCategory{
		{
			Name: "Create new Forge",
			Links: []components.SBLink{
				{
					Name: "1. Select a repository",
					Link: "/a/panel/forge/new",
				},
				{
					Name: "2. Choose a name",
					Link: "/a/panel/forge/new/name",
				},
				{
					Name: "3. Create default target",
					Link: "/a/panel/forge/new/target",
				},
			},
		},
		{
			Name: "Legal documents",
			Links: []components.SBLink{
				{
					Name: "Terms of Service",
					Link: "https://liphium.com/legal/terms",
				},
				{
					Name: "Privacy Policy",
					Link: "https://liphium.com/legal/terms",
				},
			},
		},
	})
}

var _ = templruntime.GeneratedTemplate
