// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package forge_views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Liphium/magic/backend/views/components"

func NewForgeStep1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col justify-start items-start\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.TextHeroLarge("Create Forge").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Step 1 --><div class=\"flex flex-row w-full\"><div class=\"flex flex-col mr-4\"><h2 class=\"flex justify-center items-center font-bold text-3xl bg-background2 border-[3px] rounded-full border-accent min-w-[60px] min-h-[60px]\">1.</h2><div class=\"border-dashed border-accent border-l-[3px] ml-[28.5px] h-full\"></div></div><div class=\"flex flex-col w-full min-h-80 gap-4\"><h2 class=\"font-bold text-3xl leading-[1.2] mt-[13px]\">Select a repository</h2><div class=\"flex flex-row w-full items-center justify-between\"><p class=\"text-middle-text\">Select a repository from the installations below.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.PanelCallToActionHTMX("Link more repositories", "/a/panel/installations").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div hx-get=\"/a/panel/_forms/repository/installations\" hx-swap=\"outerHTML\" hx-headers=\"{&#34;M-SubmitURL&#34;: &#34;/a/panel/forge/new&#34;}\" hx-trigger=\"load\"><p>Loading repositories..</p></div></div></div><!-- Step 2 --><div class=\"flex flex-row w-full\"><div class=\"flex flex-col mr-4\"><h2 class=\"flex justify-center items-center font-bold text-3xl bg-background2 border-[3px] rounded-full border-accent min-w-[60px] min-h-[60px]\">2.</h2><div class=\"border-dashed border-accent border-l-[3px] ml-[28.5px] h-full\"></div></div><div class=\"flex flex-col w-full min-h-80 gap-4\"><h2 class=\"font-bold text-3xl leading-[1.2] mt-[13px]\">Choose a name</h2><p>We need some kind of choose name thing here</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
